README.md

- added list of xmpp clients, prosody as xmpp server to messengers
- added iredmail to email as run your own server
- added indieweb to social networks

free xmpp services list link; iredmail; indieweb

---

README.md

https://steemit.com/faq.html#What_is_Steemit_com

Add Steemit to social networks.

---

README.md

New service here you are the products and alternative

Service and alternatives

---

README.md

I think Mega is a good alternative to the likes of dropbox and google drive in terms of privacy and security. It has end-to-end encryptions and claim to have no way of decrypting the data as they don't know the keys.

Add Mega to cloud providers list

---

README.md

mastodon.social is just a Mastodon instance

Fix Mastodon links

---

README.md

I added Wickr to Messagers as an Alternative

Added Wickr

---

README.md

Research and insigths on next-generation trust systems, decentralization and social network protocols. See also http://www.weboftrust.info/#fh5co-tab-feature-center3
PS. This a suggestion. If you think this doesn't fit here, feel free to close the PR :)

Add 'Rebooting the Web-ofTrust' entry

---

README.md

See: https://gitlab.com/prism-break/prism-break

PRISM Break has been moved to GitLab

---

README.md

Added another popular VPN provider that takes anonymity very seriously. https://mullvad.net/en/help/no-logging-data-policy/
Not to mention it is based in a country with very good data protection laws, making this a suitable candidate for the list.

Added provider to VPN section

---

README.md

Privacy policy: https://disroot.org/en/privacy_policy
Disclaimer: I am not affiliated with the service.
Disroot is an aggregate of the following:
* email,
* cloud,
* forums,
* xmpp chat,
* etherpad,
* ethercalc (real-time collaboration spreadsheets, think google docs),
* pastebin
* encrypted file upload
* search engine
* tool for making polls
* project board

Add Disroot page to related list

---

README.md

Thanks for maintaining this list, it's been really useful to me over-and-over again :)

Adds another related link

---

readme.md

Disclaimer: I am the developer of this project.

Add yeeturl

---

readme.md

Great list for privacy-enthusiasts! I really like [LBRY.tv](https://lbry.tv) as an open source video sharing platform and thought it would work well here. It integrates nicely with YouTube for creators making it easy to import/sync videos over. Privacy YouTuber, [Techlore](https://techlore.tech), hosts [his videos](https://lbry.tv/@techlore:3) there as well.

Add LBRY.tv as a Video Sharing Alternative

---

readme.md

Include Private Front-ends to Social Networks

---

readme.md

Update Riot and Ring entries

---

readme.md

> Pleroma is a free, federated social networking server built on open protocols. It is compatible with GNU Social, Mastodon, and many other ActivityPub implementations.
[Source](https://pleroma.social)

Add proper description of Pleroma

---

readme.md

- removed Qwant as data is collected and shared with third parties
https://about.qwant.com/en/legal/confidentialite/
https://tosdr.org/en/service/527
- added Session
- added IVPN
- added CalyxOs, GrapheneOs, DivestOS
- added Bromite
- removed CurePrivacy as website isn't available anymore.

Few additions and deletions.

---

readme.md

We could remove Bromite as well if OK for you.
It seems to have way less features than Kiwi Browser and I struggle to find any upsides at all compared to Kiwi Browser.

README — Add Kiwi Browser

---

readme.md

I added Fedora since it's one of the most popular reccomendations for user-friendly linux distros and this list lacked a normal linux distro

A few additions

---

readme.md

https://github.com/liameno/librengine Privacy Web Search Engine

Add librengine
